cnn: 'resnet101'
transformation:
  resize:
    w: 356
    h: 356
  mean:
    - 0.485
    - 0.456
    - 0.405
  std:
    - 0.229
    - 0.224
    - 0.225
  rhfp: 0.2
  rvfp: 0.2
  rrd: 90
  image_size:
    w: 224
    h: 224
pretrained: False
embed_size: 1024
hidden_size: 1024
num_layers: 2
lr: 0.0001
num_workers: 4
batch_size:
  train: 128
  test: 1
partial_fine_tune: True
